GET http://localhost:5000/api/repo
Cache-Control: no-cache
Content-Type: application/json
Accept: application/json

###

POST http://localhost:5000/api/repo/test
Cache-Control: no-cache
Content-Type: application/json
Accept: application/json

###

GET http://localhost:5000/api/repo/test
Cache-Control: no-cache
Content-Type: application/json
Accept: application/json

###

PUT http://localhost:5000/api/repo/test
Cache-Control: no-cache
Content-Type: application/json
Accept: application/json

{
    "test": "stuff2"
}

###